// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0vz1y9QGQv48IX49AGrD-K_R9KptMab0',
    appId: '1:651395639357:web:fec5b4528221ad4adce254',
    messagingSenderId: '651395639357',
    projectId: 'fitness-9617f',
    authDomain: 'fitness-9617f.firebaseapp.com',
    storageBucket: 'fitness-9617f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgyC6DQhlCxim0IsWIm4l4Vw9OAVjyNDA',
    appId: '1:651395639357:android:9344a5c9db83f3bcdce254',
    messagingSenderId: '651395639357',
    projectId: 'fitness-9617f',
    storageBucket: 'fitness-9617f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjSS_sezVm9y32RVRQK6nwZQjYjRTyNPE',
    appId: '1:651395639357:ios:8209521f606191f1dce254',
    messagingSenderId: '651395639357',
    projectId: 'fitness-9617f',
    storageBucket: 'fitness-9617f.firebasestorage.app',
    iosBundleId: 'com.example.myfitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjSS_sezVm9y32RVRQK6nwZQjYjRTyNPE',
    appId: '1:651395639357:ios:8209521f606191f1dce254',
    messagingSenderId: '651395639357',
    projectId: 'fitness-9617f',
    storageBucket: 'fitness-9617f.firebasestorage.app',
    iosBundleId: 'com.example.myfitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0vz1y9QGQv48IX49AGrD-K_R9KptMab0',
    appId: '1:651395639357:web:0bfa4bd3e18c03dfdce254',
    messagingSenderId: '651395639357',
    projectId: 'fitness-9617f',
    authDomain: 'fitness-9617f.firebaseapp.com',
    storageBucket: 'fitness-9617f.firebasestorage.app',
  );

}